name: BTEGGamemode
version: ${project.version}
main: de.leander.bteggamemode.BTEGGamemode
authors: [ Leander ]
description: This plugin sets users gamemode to spectator or visitor (checks for permission node) when a player joins a server.
website: bte-germany.de

commands:
  bteg:
    description: Restarts the server within 2 minutes
    usage: /bteg restart
  terraform:
    description: Terraforms an area for you
    usage: /terraform <Height>
  speed:
    description: Gives you speed
    usage: /speed <Number>
  /side:
    description: Replaces blocks sideways
    usage: //side <Block-ID> <Block-ID> <Direction[n,e,s,w]>
  cleanup:
    description: Executes big worldedit command
    usage: /cleanup
    aliases:
      - /cleanup